@echo off
echo Enabling pdo_mysql extension...
powershell -Command "(Get-Content 'C:\Program Files\php-8.4.12\php.ini') -replace ';extension=pdo_mysql','extension=pdo_mysql' | Set-Content 'C:\Program Files\php-8.4.12\php.ini'"
echo Done! Press any key to close...
pause >nul
